-- EduMap Cloud: ejecutar en Supabase > SQL Editor
create extension if not exists pgcrypto;

create table if not exists institutions (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  lat double precision,
  lng double precision,
  created_at timestamptz default now()
);

create table if not exists buildings (
  id bigint generated by default as identity primary key,
  institution_id bigint references institutions(id) on delete cascade,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists floors (
  id bigint generated by default as identity primary key,
  building_id bigint references buildings(id) on delete cascade,
  level integer not null,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists navigation_nodes (
  id bigint generated by default as identity primary key,
  name text not null,
  floor_id bigint references floors(id) on delete set null,
  lat double precision,
  lng double precision,
  x double precision default 0,
  y double precision default 0,
  created_at timestamptz default now()
);

create table if not exists spaces (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  space_type text default 'sala',
  floor_id bigint references floors(id) on delete set null,
  node_id bigint references navigation_nodes(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists navigation_edges (
  id bigint generated by default as identity primary key,
  from_node_id bigint references navigation_nodes(id) on delete cascade,
  to_node_id bigint references navigation_nodes(id) on delete cascade,
  weight double precision not null default 1,
  accessible boolean not null default true,
  created_at timestamptz default now(),
  unique(from_node_id,to_node_id)
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check(role in ('user','admin')),
  display_name text,
  created_at timestamptz default now()
);

create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  space_id bigint references spaces(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, space_id)
);

alter table institutions enable row level security;
alter table buildings enable row level security;
alter table floors enable row level security;
alter table navigation_nodes enable row level security;
alter table spaces enable row level security;
alter table navigation_edges enable row level security;
alter table profiles enable row level security;
alter table favorites enable row level security;

-- Público: el mapa puede leerse sin iniciar sesión.
drop policy if exists "public read institutions" on institutions;
create policy "public read institutions" on institutions for select using (true);
drop policy if exists "public read buildings" on buildings;
create policy "public read buildings" on buildings for select using (true);
drop policy if exists "public read floors" on floors;
create policy "public read floors" on floors for select using (true);
drop policy if exists "public read nodes" on navigation_nodes;
create policy "public read nodes" on navigation_nodes for select using (true);
drop policy if exists "public read spaces" on spaces;
create policy "public read spaces" on spaces for select using (true);
drop policy if exists "public read edges" on navigation_edges;
create policy "public read edges" on navigation_edges for select using (true);

-- Perfil: cada usuario puede leer su propio perfil.
drop policy if exists "read own profile" on profiles;
create policy "read own profile" on profiles for select using (auth.uid() = id);

-- Favoritos: cada usuario administra solo los suyos.
drop policy if exists "read own favorites" on favorites;
create policy "read own favorites" on favorites for select using (auth.uid() = user_id);
drop policy if exists "insert own favorites" on favorites;
create policy "insert own favorites" on favorites for insert with check (auth.uid() = user_id);
drop policy if exists "delete own favorites" on favorites;
create policy "delete own favorites" on favorites for delete using (auth.uid() = user_id);

-- Crear perfil automáticamente al registrarse.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
